on: push
name: 🚀 Deploy website perizinan on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: Remove htaccess development
      run: rm .htaccess
    - name: Rename .htaccess production.file to index.php
      run: php -r "file_exists('.htaccess') || copy('.htaccess production', '.htaccess');"
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
